### ISSUE TITLE
Error 200 on jailbroken device 

### ISSUE THREAD

**Issue by ethanhines** [MiRO92/uYou-for-YouTube#124] opened 2022-04-01 05:32 UTC
Device info:

iOS/iPadOS version: 14.3
Device model: iPad 7 Generation 
Sideload tool: n/a
Version of uYou: v2.1
Describe the bug:

 I'm getting an error that says:
Error 200 Download check failed file:///var/mobile/Containers/Application/[hex]/library/caches/uYou/[hex].unknown The operation could not be completed NSURLE Error domain error 1008 on the video only audio downloads without error.

How to reproduce the bug:
(Please attach videos or screenshots if possible)

I'm in a jailbroken  state and I but I'm unable to download the video since It seems there is a domain/Url error.

When I use cercube I can download the videos without issues but I like more uYou because it’s completely free

**Comment by Skywalker8510** [comment] 2022-05-21 11:34
duplicate of #177

**Closed** 2023-04-08 20:48 UTC
