### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by PabloButron** [MiRO92/uYou-for-YouTube#113] opened 2022-02-11 11:45 UTC
my download speed is like 20-30 kbps, my bet is that the servers are saturated, I have my own private vps and I want use it to increase my download speed, maybe it can helps but I don't know how to proceed, is there any setting to do it possible?

**Comment by Macleykun** [comment] 2022-02-14 23:06
No.
You can’t add your own server to the YouTube cdn pool.
It’ll change trough the day, you can’t do much if the problem isn’t your WiFi.

**Comment by theoccurrence** [comment] 2022-03-17 10:50
> No.
> 
> You can’t add your own server to the YouTube cdn pool.
> 
> It’ll change trough the day, you can’t do much if the problem isn’t your WiFi.

You can constantly pause and restart the download to speed it up considerably. I have no idea why though.

**Comment by farbix** [comment] 2022-03-19 16:01
> > No.
> > You can’t add your own server to the YouTube cdn pool.
> > It’ll change trough the day, you can’t do much if the problem isn’t your WiFi.
> 
> You can constantly pause and restart the download to speed it up considerably. I have no idea why though.

is Miro dead or something?

**Comment by Nordii08** [comment] 2022-03-19 21:45
The slow download speed is EXTREMELY annoying. What should take less than a minute to download ends up taking over 20 minutes.

**ASSUMPTION BASED OFF OF BEHAVIOUR -- TAKE WITH A GRAIN OF SALT**
seems like this tweak uses _youtube-dl_ code, which has been **severely** throttled for a few months now.
_yt-dlp_ doesn't have this issue, however. Maybe this could be fixed by replacing the _youtube-dl_ code with _yt-dlp_ code?
(If this isn't how this tweak works at all, I'm sorry)

**Comment by wild-a** [comment] 2022-04-08 05:35
The download speed is unbearably slow. I can download 4K HDR movies from somewhere else in 5 minutes, but a 500MB file takes 2 hours in uYou.

**Closed** 2023-04-08 20:47 UTC
