### ISSUE TITLE
Downloads do not work

### ISSUE THREAD

**Issue by korboybeats** [MiRO92/uYou-for-YouTube#128] opened 2022-04-19 14:25 UTC
Device info:

iOS/iPadOS version: iPadOS 15.3.1
Device model: M1 iPad Pro 2021
Sideload tool: Signulous
Version of uYou: v16.42.3_2.1
Describe the bug:

I get Error 200 when trying to download any videos 

How to reproduce the bug:

https://user-images.githubusercontent.com/80824905/164027832-5bd6e752-dc8d-4ea1-99ee-d31dcd6ada42.MOV

**Comment by t0mi** [comment] 2022-04-20 16:41
Same on iPhone 13 Pro | iOS 15.1.1  latest sideload ipa without jailbreak

**Comment by AngealAuditore** [comment] 2022-04-21 03:40
Hi any luck with that problem? I been trying to figure out why this happens, when I download the ipa from here the problem appears, but if I download the ipa directly from appdb with my cetificates on the appdb website the downloads on the uyou app work any ideas

**Comment by Tweaker177** [comment] 2022-05-08 15:12
I think a recent update changed where the offline content is stored, and they seem to have made it a little more difficult to just grab the files, as the audio and video are split up, and they have a metadata file in each media folder specifying where the audio is, and where the video(s) are, most are split at least in two.  

Previously there was a folder I had favorited in Filza as YTOffline_2736383637373 (the numbers are different too lazy to copy).

That folder no longer exists in the latest YouTube app(actually it was moved, but the contents are slightly different).  

Now downloaded content goes to "/Contaimers/Data/Application/YouTube's long identifier/Library/ApplicationSupport/Media/Offline/YTOffline_10309554950735915****/individualDLFolder/media"

**** I appended this string in case the long number is an identifier unique to my account. (I haven't looked into YouTube very much until recently.)

*individualDLFolder = unique folder string for each DL

Also in the same URL is "/metadata".  The metadata has an expiration date or a keep alive depending on Premium status, as well as a tokenID and other required items for the media file to play once renamed with the proper extension.

Here is a sample metadata for one of my downloads, which may be different as I have the paid YouTube membership.  Anyways you can see what it's asking for and values that work, just please don't use any personally identifying info. 


Example metadata.data file needed for download to play outside of YouTube app, and I imagine to play at all if the expiration date or time comes.

- [code]

https://rr1---sn-hp57kn6r.googlevideo.com/videoplayback?expire=1651931647&ei=nyV2YvPaFaml0_wPppWcmA4&ip=98.211.197.221&id=o-ADYSprEFcgeCFXhEyXdlQLnTAKiGCIn1nbacXsZwj6Xf&itag=278&source=youtube&requiressl=yes&mh=EG&mm=31%2C26&mn=sn-hp57kn6r%2Csn-5uaeznr6&ms=au%2Conr&mv=m&mvi=1&pl=18&ctier=O&pfa=5&initcwndbps=2738750&hightc=yes&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=3844317&ratebypass=yes&dur=429.678&lmt=1651901228485667&mt=1651909755&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=IOS&txp=4437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Chightc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgVDLDx_zADaHd-Gcnvf9RYfqT56syBrDwyfDpJqBiY98CIHQnEezaKirnu0N2GZgZHxcbFR8_f26xvd9pC34su9aW&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIhs22GNp05NOOMw9BW5yEgHB5Nhu6kvDB84pgWS9oBQAiAnKMJfHjK4JqJdab7MYdBHlBLfXaRUvnKoQ4qsynFqdw%3D%3D*video/webm; codecs="vp9"08@J ÚRÛ ¢X£¶ÏÓÌ÷`ÝÑêtinyÈÒ144pØø¯àî5F5h-iM9BvFjWagm[/code]

Hope this is of some help. If not sorry for wasting your time. 
-Brian / i0stweak3r

**Comment by Tweaker177** [comment] 2022-05-08 15:27
> Hi any luck with that problem? I been trying to figure out why this happens, when I download the ipa from here the problem appears, but if I download the ipa directly from appdb with my cetificates on the appdb website the downloads on the uyou app work any ideas

Most likely the appdb has an older version of YouTube, as I believe it is the most recent update that broke it.

**Comment by Skywalker8510** [comment] 2022-05-21 11:33
duplicate of 177

**Closed** 2024-02-08 03:28 UTC
