### ISSUE TITLE
Settings return to the initial state randomly

### ISSUE THREAD

**Issue by asteria121** [MiRO92/uYou-for-YouTube#106] opened 2022-01-14 04:39 UTC
![175F6339-4BD3-4917-8432-7AE74964B2E9](https://user-images.githubusercontent.com/24371508/149452171-31b421a1-4962-4b4a-b0bb-3cb895e6cdc6.png)
Settings like video overlay setting, PiP button setting, auto play next video, account info, general settings, etc return to the initial state like above picture(uYou initial launch screen). I'm using iphone 13 pro max on ios 15.0.2 and sideloaded uYou 2.1 ipa with developer account. It usually happens once a day randomly.

**Comment by qnblackcat** [comment] 2022-01-14 07:03
Duplicate of https://github.com/MiRO92/uYou-for-YouTube/issues/75

are you using Signum/Signulous?

**Comment by tree8069** [comment] 2022-01-14 14:48
I'm using ESign(?) used in jbsite.kr
![A16BF002-D338-4AC7-B525-23B59958DCFB](https://user-images.githubusercontent.com/24371508/149534658-19973749-36ea-4533-b57e-e7f4c4417ab4.png)

**Comment by tree8069** [comment] 2022-01-14 14:50
![7EBAFAD9-94F3-4E7D-8FFE-6A7DFF05801A](https://user-images.githubusercontent.com/24371508/149534950-f26f1075-3655-42bc-94b5-e02c99fe326e.jpeg)
Sideloaded like this (masked developer name and code)

**Comment by qnblackcat** [comment] 2022-01-14 15:41
IIRC, both Signum and Signulous aree based on [**Zsign**](https://github.com/zhlynn/zsign).
I’m not sure what technology are Esign using. If it related to **Zsign**, then it probably can have the same problem.
And no, I don’t think that using a developer certificate makes any difference

**Closed** 2024-02-07 05:54 UTC
